### ISSUE TITLE
win32-eventlog not working in the instance vagrant in kitchen ci test

### ISSUE THREAD

**Issue by LyTuan** [chef/win32-eventlog#33]
## Description

I run kitchen test and I use win32-eventlog to read event in the vagrant box. Actually, the win32-eventlog only read the local machine run the `kitchen test`.  I try to pass the param server to the initialize function, but it not working 
## Gem Version
3.0.3

## Windows Version
Window 10 Pro version 2019

## Replication Case

```  Win32::EventLog.read("MyApp","win2k12r2") do |log|
          Inspec::Log.info(log.description)
          Inspec::Log.info(log)
     end
```
How can I pass the server param is a vagrant virtual box?

Many thanks,

**Comment by mwrock** [comment]
Its a little difficult to diagnose the issue here with the info given. Can you shown how and where you are initializing the `EventLog` instance and what the error is you are receiving?

Thanks!

**Comment by mwrock** [comment]
I did a little research here and discovered that remotely accessing event logs is likely not going to be feasible with this gem. This gem wraps the win32 function `OpenEventLog` which will use the security context of the local user. This would probably only work on a remote server in a AD environment using an AD account with the correct permissions on the remote machine to view its event logs.

In a vagrant or TK context, you would probably need to use the winrm gem and use powershell to call `Get-Eventlog`.
